# Enable gofmt linter in addition to default set of linters
# https://golangci-lint.run/usage/linters/#enabled-by-default
linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  exclude-rules:
    - linters:
        - errcheck
      source: "^\\s*defer\\s+"
