name: Code Tests
on: [push, pull_request]
jobs:
  code_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install GoLint
        run: |
          go get -u golang.org/x/lint/golint

      - name: Unit tests
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
