name: Code Tests
on: [push, pull_request]
jobs:
  code_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Unit tests
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
